name: build pyjava
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,16 * *"
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".github/**"
permissions:
  actions: read
  packages: write
  contents: read
jobs:
  push:
    name: "pyjava:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '3.9'
          - '3.10'
          - '3.11'

    steps:
      - uses: actions/checkout@v3

      - name: Setup QEMU for multiarch build
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/MCCbena/pyjava:${{ matrix.tag }}
